# Copyright 2026 ResQ
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""DTSOP domain models for the ResQ MCP server."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, ValidationInfo, field_validator

from resq_mcp.core.validation import (
    MAX_IDENTIFIER_LENGTH,
    validate_identifier,
    validate_parameters,
)


class SimulationRequest(BaseModel):
    """Request for high-fidelity physics simulation in digital twin.

    Part of DTSOP system. Triggers physics-based simulation in Unity/Unreal
    Engine for accurate disaster propagation modeling and strategy validation.

    Attributes:
        scenario_id: Unique scenario identifier for this simulation.
        sector_id: Geographic sector to simulate.
        disaster_type: Type of disaster to model (e.g., "flood", "wildfire").
        parameters: Simulation parameters (e.g., {"wind_speed": 15.5, "water_level": 2.3}).
        priority: Processing priority (standard queued, urgent fast-tracked).

    Note:
        Simulations run asynchronously. Monitor progress via the returned
        simulation ID and resource subscription (resq://simulations/{id}).
    """

    scenario_id: str = Field(..., min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
    sector_id: str = Field(..., min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
    disaster_type: str = Field(..., min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
    parameters: dict[str, float | str]  # e.g., wind_speed, water_level
    priority: Literal["standard", "urgent"] = "standard"

    @field_validator("scenario_id", "sector_id", "disaster_type")
    @classmethod
    def _validate_identifier_fields(cls, value: str, info: ValidationInfo) -> str:
        """Reject identifiers outside the allow-list (injection/traversal defense)."""
        return validate_identifier(value, field=info.field_name or "identifier")

    @field_validator("parameters")
    @classmethod
    def _validate_parameter_bounds(cls, value: dict[str, float | str]) -> dict[str, float | str]:
        """Bound the size of the parameters mapping and its string values."""
        return validate_parameters(value)


class OptimizationStrategy(BaseModel):
    """Reinforcement learning-optimized deployment and evacuation strategy.

    Part of DTSOP system. Generated by RL agents trained on thousands of
    simulated disaster scenarios to optimize resource allocation and
    evacuation routing under various constraints.

    Attributes:
        strategy_id: Unique strategy identifier (e.g., "STRAT-X1Y2Z3W4").
        related_alert_id: Pre-alert or incident ID this strategy addresses.
        recommended_deployment: Mapping of drone types to recommended counts
                                (e.g., {"surveillance": 2, "payload": 1}).
        evacuation_routes: Ordered list of recommended evacuation routes.
        estimated_success_rate: Predicted success probability (0.0 to 1.0)
                                based on simulation outcomes.
        simulation_proof_url: NeoFS/IPFS URL for simulation evidence and logs.

    Note:
        Success rate derived from Monte Carlo simulations across varying
        disaster intensities and communication scenarios.
    """

    strategy_id: str
    related_alert_id: str | None = None
    recommended_deployment: dict[str, int]  # drone_type -> count
    evacuation_routes: list[str]
    estimated_success_rate: float
    simulation_proof_url: str | None = None
